# Generated by Django 5.2.16 on 2026-07-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(default='Main Campus', max_length=150),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(default='active', max_length=30),
        ),
    ]
