# Generated by Django 5.2.16 on 2026-07-23 08:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_remove_interview_candidate_remove_interview_tenant_and_more'),
        ('tenants', '0002_subscriptionplan_alter_tenant_options_and_more'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='leave_type_name',
            field=models.CharField(default='Annual Leave', max_length=100),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='used_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='attachment_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='days_requested',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hr_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type_name',
            field=models.CharField(default='Annual Leave', max_length=100),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='supervisor_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflowinstance'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('supervisor_approved', 'Supervisor Approved'), ('hr_approved', 'HR Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('default_days_per_year', models.IntegerField(default=20)),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_document', models.BooleanField(default=False)),
                ('allow_encashment', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('salary_grade', models.CharField(default='all', max_length=50)),
                ('allowed_days', models.IntegerField(default=20)),
                ('accrual_frequency', models.CharField(default='annual', max_length=30)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='hr.leavetype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveEncashment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('days_to_encash', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(default='submitted', max_length=30)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encashments_approved', to='hr.employeeprofile')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encashments', to='hr.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.leavetype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.leavetype'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.leavetype'),
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('is_recurring', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='leavetype',
            index=models.Index(fields=['tenant', 'is_deleted'], name='hr_leavetyp_tenant__c01227_idx'),
        ),
        migrations.AddIndex(
            model_name='leavepolicy',
            index=models.Index(fields=['tenant', 'is_deleted'], name='hr_leavepol_tenant__718ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveencashment',
            index=models.Index(fields=['tenant', 'is_deleted'], name='hr_leaveenc_tenant__9cb7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='publicholiday',
            index=models.Index(fields=['tenant', 'is_deleted'], name='hr_publicho_tenant__b587ff_idx'),
        ),
    ]
