# Generated by Django 5.2.16 on 2026-07-23 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_leavebalance_leave_type_name_leavebalance_used_days_and_more'),
        ('tenants', '0002_subscriptionplan_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollrun',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='payrollrun',
            name='earnings',
        ),
        migrations.RemoveField(
            model_name='payrollrun',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payrollrun',
            name='net_pay',
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='calculation_version',
            field=models.CharField(default='V1', max_length=30),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='minimum_wage_version',
            field=models.CharField(default='V1', max_length=30),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='pension_rules_version',
            field=models.CharField(default='V1', max_length=30),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='tax_rules_version',
            field=models.CharField(default='V1', max_length=30),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_gross',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_pension',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='other_allowances',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='pension_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='tax_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='PayrollGLAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollAccountingConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('bonus_expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bonus_expense_configs', to='hr.payrollglaccount')),
                ('gratuity_provision_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gratuity_provision_configs', to='hr.payrollglaccount')),
                ('itf_liability_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itf_liability_configs', to='hr.payrollglaccount')),
                ('leave_accrual_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_accrual_configs', to='hr.payrollglaccount')),
                ('net_salary_liability_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='net_salary_liability_configs', to='hr.payrollglaccount')),
                ('nhf_liability_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nhf_liability_configs', to='hr.payrollglaccount')),
                ('nsitf_liability_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nsitf_liability_configs', to='hr.payrollglaccount')),
                ('overtime_expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overtime_expense_configs', to='hr.payrollglaccount')),
                ('paye_liability_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paye_liability_configs', to='hr.payrollglaccount')),
                ('pension_liability_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pension_liability_configs', to='hr.payrollglaccount')),
                ('salary_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_expense_configs', to='hr.payrollglaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollPayslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pension_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pension_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('nhf_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('nhf_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('salary_grade', models.CharField(max_length=50)),
                ('employment_type', models.CharField(default='full_time', max_length=50)),
                ('tax_rule_version', models.CharField(default='V1', max_length=30)),
                ('pension_rule_version', models.CharField(default='V1', max_length=30)),
                ('nhf_rule_version', models.CharField(default='V1', max_length=30)),
                ('calculation_version', models.CharField(default='V1', max_length=30)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.employeeprofile')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.payrollrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='payrollglaccount',
            index=models.Index(fields=['tenant', 'is_deleted'], name='hr_payrollg_tenant__5d3179_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollaccountingconfiguration',
            index=models.Index(fields=['tenant', 'is_deleted'], name='hr_payrolla_tenant__593ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollpayslip',
            index=models.Index(fields=['tenant', 'is_deleted'], name='hr_payrollp_tenant__f7b108_idx'),
        ),
    ]
