# Generated by Django 5.2.16 on 2026-07-27 12:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_payrollpayslip_absent_days_and_more'),
        ('tenants', '0002_subscriptionplan_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='bvn_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='campus_name',
            field=models.CharField(default='Main Campus', max_length=150),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='company_name',
            field=models.CharField(default='EduOrbit Group', max_length=150),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='cost_centre',
            field=models.CharField(default='CC-101-ACADEMICS', max_length=100),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='department_name',
            field=models.CharField(default='General Academics', max_length=150),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='directorate_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='division_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='is_bvn_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='is_nin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='kyc_verification_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='lifecycle_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_verification', 'Pending Verification'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('probation', 'Probation'), ('confirmed', 'Confirmed'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('retired', 'Retired'), ('archived', 'Archived')], default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='nin_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='pfa_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='rsa_pin_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='tax_id_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='team_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='unit_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('permanent', 'Permanent'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('consultant', 'Consultant'), ('volunteer', 'Volunteer'), ('intern', 'Intern'), ('nysc', 'NYSC Corp Member'), ('adjunct', 'Adjunct Teacher'), ('visiting', 'Visiting Lecturer')], default='full_time', max_length=30),
        ),
        migrations.CreateModel(
            name='CompensationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('effective_start_date', models.DateField(default=django.utils.timezone.now)),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_code', models.CharField(default='NGN', max_length=10)),
                ('salary_grade', models.CharField(default='grade_1', max_length=50)),
                ('change_reason', models.CharField(blank=True, max_length=200)),
                ('is_current', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_history', to='hr.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'is_deleted'], name='hr_compensa_tenant__f868d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('contract_type', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_history', to='hr.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'is_deleted'], name='hr_contract_tenant__f24681_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('department_name', models.CharField(default='General Academics', max_length=150)),
                ('campus_name', models.CharField(default='Main Campus', max_length=150)),
                ('cost_centre', models.CharField(default='CC-101-ACADEMICS', max_length=100)),
                ('max_headcount', models.PositiveIntegerField(default=1)),
                ('filled_headcount', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'is_deleted'], name='hr_jobposit_tenant__514581_idx')],
            },
        ),
    ]
