# Generated by Django 5.2.16 on 2026-07-27 13:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_onboardingdraft'),
        ('tenants', '0002_subscriptionplan_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('workflow_type', models.CharField(choices=[('leave', 'Leave Approval Workflow'), ('attendance_adjustment', 'Attendance Adjustment Workflow'), ('recruitment', 'Recruitment Hiring Workflow'), ('promotion', 'Promotion Workflow'), ('transfer', 'Employee Transfer Workflow'), ('salary_increment', 'Salary Increment Workflow'), ('exit', 'Offboarding Exit Workflow')], max_length=50)),
                ('steps_config', models.JSONField(default=list, help_text="List of approval step objects: [{'step': 1, 'role': 'hod'}, {'step': 2, 'role': 'principal'}]")),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'is_deleted'], name='hr_approval_tenant__83be38_idx')],
            },
        ),
    ]
