# Generated by Django 5.2.16 on 2026-07-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_approvalworkflow'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hrsettings',
            name='hr_hrsettin_tenant__cba814_idx',
        ),
    ]
