# Generated by Django 5.2.16 on 2026-08-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_remove_hrsettings_hr_hrsettin_tenant__cba814_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='nhf_number',
            field=models.CharField(blank=True, help_text='National Housing Fund (FMBN) contribution ID', max_length=50),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='nhis_number',
            field=models.CharField(blank=True, help_text='National Health Insurance Scheme ID', max_length=50),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='nsitf_number',
            field=models.CharField(blank=True, help_text='Nigeria Social Insurance Trust Fund (Employee Compensation) ID', max_length=50),
        ),
    ]
