# Generated by Django 5.2.16 on 2026-08-01 21:30

import backend.apps.hr.models.employee
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_employeeprofile_nhf_number_and_more'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='original_photo',
            field=models.ImageField(blank=True, null=True, upload_to=backend.apps.hr.models.employee.employee_original_path),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=backend.apps.hr.models.employee.employee_photo_path),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='photo_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='photo_replacement_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='photo_source',
            field=models.CharField(blank=True, default='HR_UPLOAD', max_length=30),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='photo_status',
            field=models.CharField(blank=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='photo_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=backend.apps.hr.models.employee.employee_thumb_path),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='photo_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_employee_photos', to='people.person'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='photo_verification_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='photo_verification_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='photo_verification_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='photo_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
