# Generated by Django 5.2.16 on 2026-08-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_employeeprofile_original_photo_employeeprofile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='photo_hash',
            field=models.CharField(blank=True, help_text='SHA256 checksum of processed active photo', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='photo_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='photo_processing_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Processing time, compression ratio, telemetry'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='photo_size',
            field=models.IntegerField(blank=True, help_text='Active photo size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='photo_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
