# Generated by Django 5.2.16 on 2026-07-17 21:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
        ('tenants', '0002_subscriptionplan_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentlicense',
            name='device_limit',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='contentlicense',
            name='printing_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningcontentversion',
            name='accessibility_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='active_time_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='last_device',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='offline_sync_status',
            field=models.CharField(default='synced', max_length=30),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='pause_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='resume_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DigitalLibraryResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=255)),
                ('category', models.CharField(default='pdf', max_length=50)),
                ('visibility', models.CharField(choices=[('platform', 'Platform Wide'), ('tenant', 'Tenant Group Wide'), ('school', 'School Wide'), ('department', 'Department Wide'), ('personal', 'Private Personal')], default='school', max_length=30)),
                ('tags_metadata', models.JSONField(blank=True, default=dict)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.school')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='library_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.digitallibraryresource'),
        ),
        migrations.CreateModel(
            name='LearningSearchIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('search_keywords', models.TextField()),
                ('subject_code', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=150)),
                ('content_id', models.UUIDField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.school')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfflinePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('zip_file_path', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.school')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfflineManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('resource_path', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifests', to='lms.offlinepackage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='digitallibraryresource',
            index=models.Index(fields=['tenant', 'is_deleted'], name='lms_digital_tenant__403dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsearchindex',
            index=models.Index(fields=['tenant', 'is_deleted'], name='lms_learnin_tenant__1a84b2_idx'),
        ),
        migrations.AddIndex(
            model_name='offlinepackage',
            index=models.Index(fields=['tenant', 'is_deleted'], name='lms_offline_tenant__95b457_idx'),
        ),
        migrations.AddIndex(
            model_name='offlinemanifest',
            index=models.Index(fields=['tenant', 'is_deleted'], name='lms_offline_tenant__d1d290_idx'),
        ),
    ]
