name: eduorbit_design_system
description: "EduOrbit Design System containing all reusable UI components."
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10
  shimmer: ^3.0.0
  fl_chart: ^0.65.0 # For bar and pie charts
  mobile_scanner: ^3.5.2 # For QR scanning
  qr_flutter: ^4.1.0 # For QR display

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
