# Generated by Django 5.2.16 on 2026-07-29 17:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_subject_category_subjectcategory'),
        ('people', '0001_initial'),
        ('tenants', '0003_remove_subscriptionplan_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPromotionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('promoted_count', models.IntegerField(default=0)),
                ('retained_count', models.IntegerField(default=0)),
                ('executed_by_user_id', models.UUIDField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear')),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='academic.academicclass')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('to_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='academic.academicclass')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'is_deleted'], name='academic_ba_tenant__c090e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='GradebookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('ca_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('exam_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('letter_grade', models.CharField(blank=True, max_length=10)),
                ('remark', models.CharField(blank=True, max_length=100)),
                ('is_absent', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('teacher_notes', models.TextField(blank=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_entries', to='academic.academicclass')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.academicperiod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_entries', to='people.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_entries', to='academic.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['student__person__first_name', 'student__person__last_name'],
                'unique_together': {('student', 'subject', 'academic_class', 'academic_year', 'period')},
            },
        ),
        migrations.CreateModel(
            name='StudentReportCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('position_in_class', models.IntegerField(default=1)),
                ('class_size', models.IntegerField(default=1)),
                ('promotion_status', models.CharField(choices=[('pending', 'Pending'), ('promoted', 'Promoted'), ('retained', 'Retained'), ('conditional', 'Conditional Pass')], default='pending', max_length=30)),
                ('teacher_comments', models.TextField(blank=True)),
                ('principal_comments', models.TextField(blank=True)),
                ('affective_domain', models.JSONField(blank=True, default=dict)),
                ('psychomotor_domain', models.JSONField(blank=True, default=dict)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('qr_verification_code', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicclass')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.academicperiod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='people.studentprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-academic_year__start_date', 'student__person__first_name'],
                'unique_together': {('student', 'academic_year', 'period')},
            },
        ),
    ]
