# Generated by Django 5.2.16 on 2026-07-23 16:20

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_subscriptionplan_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('event_id', models.UUIDField(db_index=True, unique=True)),
                ('consumer_name', models.CharField(max_length=150)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event_id', 'consumer_name'), name='unique_processed_event_consumer')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_name', models.CharField(max_length=150)),
                ('aggregate_type', models.CharField(max_length=100)),
                ('aggregate_id', models.CharField(max_length=100)),
                ('aggregate_version', models.IntegerField(default=1)),
                ('sequence_number', models.BigIntegerField(default=1)),
                ('payload', models.JSONField()),
                ('payload_schema_version', models.IntegerField(default=1)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('initiated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('causation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('DEAD', 'Dead'), ('ARCHIVED', 'Archived')], db_index=True, default='PENDING', max_length=20)),
                ('published_to_broker_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_attempts', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('worker_hostname', models.CharField(blank=True, max_length=150, null=True)),
                ('worker_pid', models.IntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('broker_name', models.CharField(blank=True, max_length=50, null=True)),
                ('exchange', models.CharField(blank=True, max_length=100, null=True)),
                ('routing_key', models.CharField(blank=True, max_length=100, null=True)),
                ('queue_name', models.CharField(blank=True, max_length=100, null=True)),
                ('message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='tenants.tenant')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['payload'], name='outbox_payload_gin'), models.Index(condition=models.Q(('status__in', ['PENDING', 'FAILED'])), fields=['next_retry_at'], name='outbox_pending_retry_idx'), models.Index(fields=['status', 'locked_at'], name='outbox_status_locked_idx'), models.Index(fields=['occurred_at'], name='outbox_occurred_at_idx'), models.Index(fields=['aggregate_type', 'aggregate_id', 'sequence_number'], name='outbox_aggregate_seq_idx'), models.Index(fields=['tenant', 'correlation_id'], name='outbox_tenant_corr_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('dispatch_attempts__gte', 0)), name='outbox_dispatch_attempts_gte_0'), models.CheckConstraint(condition=models.Q(('payload_schema_version__gte', 1)), name='outbox_payload_schema_version_gte_1'), models.CheckConstraint(condition=models.Q(('sequence_number__gte', 1)), name='outbox_sequence_number_gte_1'), models.UniqueConstraint(fields=('event_id',), name='outbox_unique_event_id')],
            },
        ),
    ]
