# Generated by Django 5.2.16 on 2026-07-17 18:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_department'),
        ('people', '0001_initial'),
        ('tenants', '0002_subscriptionplan_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BellSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bell_schedules', to='tenants.school')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConflictReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('conflict_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(default='warning', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by_user_id', models.UUIDField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.school')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=40)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academic.academicclass')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_taught', to='people.person')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=40)),
                ('resource_type', models.CharField(choices=[('classroom', 'Classroom'), ('lab', 'Laboratory'), ('ict', 'ICT Room'), ('hall', 'Auditorium Hall'), ('sports', 'Sports Field'), ('bus', 'School Bus'), ('clinic', 'Clinic Room'), ('hostel', 'Hostel Hall')], default='classroom', max_length=30)),
                ('status', models.CharField(default='available', max_length=30)),
                ('availability', models.JSONField(blank=True, default=dict)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_resources', to='tenants.school')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('recurrence_rule', models.JSONField(blank=True, default=dict)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='timetable.lesson')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='timetable.resource')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.school')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('schedule_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.scheduletype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchedulingConstraint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('constraint_type', models.CharField(max_length=50)),
                ('configuration', models.JSONField(default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchedulingScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('working_days', models.JSONField(default=list)),
                ('blocked_hours', models.JSONField(default=list)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='people.person')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherSubstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='timetable.schedule')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutes', to='people.person')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherWorkloadAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('teaching_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('administrative_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('duties_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
                ('bell_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='timetable.bellschedule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='timetable.timeslot'),
        ),
        migrations.AddIndex(
            model_name='bellschedule',
            index=models.Index(fields=['tenant', 'is_deleted'], name='timetable_b_tenant__2f8c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictreport',
            index=models.Index(fields=['tenant', 'is_deleted'], name='timetable_c_tenant__80c4ec_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['tenant', 'is_deleted'], name='timetable_l_tenant__356ead_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['tenant', 'is_deleted'], name='timetable_r_tenant__c78527_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulingconstraint',
            index=models.Index(fields=['tenant', 'is_deleted'], name='timetable_s_tenant__e0d752_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulingscenario',
            index=models.Index(fields=['tenant', 'is_deleted'], name='timetable_s_tenant__442f81_idx'),
        ),
        migrations.AddIndex(
            model_name='teacheravailability',
            index=models.Index(fields=['tenant', 'is_deleted'], name='timetable_t_tenant__1cb537_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubstitution',
            index=models.Index(fields=['tenant', 'is_deleted'], name='timetable_t_tenant__3559b1_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherworkloadanalytics',
            index=models.Index(fields=['tenant', 'is_deleted'], name='timetable_t_tenant__0b827f_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['tenant', 'is_deleted'], name='timetable_t_tenant__bb9504_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['tenant', 'is_deleted'], name='timetable_s_tenant__c8311d_idx'),
        ),
    ]
