# Generated by Django 5.2.16 on 2026-07-27 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eae', '0001_initial'),
        ('lms', '0003_coursecategory_course_courselesson_quiz_quizattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='lms_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbt_exams', to='lms.quiz'),
        ),
    ]
