# Generated by Django 5.2.16 on 2026-08-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_drugdispenselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugdispenselog',
            name='dispensed_to',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='drugdispenselog',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drug_dispenses', to='clinic.patientprofile'),
        ),
    ]
