# Generated by Django 5.2.16 on 2026-07-17 16:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(db_index=True, max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('branding_config', models.JSONField(blank=True, default=dict)),
                ('settings_override', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['-created_at'],
            },
        ),
    ]
