# Generated by Django 5.2.16 on 2026-07-27 18:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('tenants', '0002_subscriptionplan_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_model',
            field=models.CharField(choices=[('SCHOOL_PAY', 'School Pay'), ('PARENT_PAY', 'Parent Pay'), ('HYBRID', 'Hybrid')], default='SCHOOL_PAY', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='cbt_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='grace_period_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='lms_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_campuses',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_staff',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_students',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='mobile_app_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='parent_portal_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='termly_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='yearly_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('TERMLY', 'Termly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='billing_model',
            field=models.CharField(default='SCHOOL_PAY', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='payment_provider',
            field=models.CharField(default='OPay', max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='modules_licensed',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('GRACE', 'Grace Period'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='TRIAL', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentPlatformSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('billing_cycle', models.CharField(default='MONTHLY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_until', models.DateTimeField()),
                ('payment_status', models.CharField(default='ACTIVE', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.subscriptionplan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_subscriptions', to='people.studentprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'is_deleted'], name='tenants_stu_tenant__15e289_idx')],
            },
        ),
    ]
