# Generated by Django 5.2.16 on 2026-08-03 14:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_batchpromotionlog_gradebookentry_studentreportcard'),
        ('people', '0001_initial'),
        ('tenants', '0003_remove_subscriptionplan_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('reminder_schedule_days', models.JSONField(default=list, help_text='List of reminder threshold days before expiry: [30, 14, 7, 3, 1, 0]')),
                ('grace_period_days_default', models.IntegerField(default=7)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('invoice_prefix', models.CharField(default='INV-', max_length=20)),
                ('receipt_prefix', models.CharField(default='REC-', max_length=20)),
                ('compliance_default_percent', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Billing Setting',
                'verbose_name_plural': 'Billing Settings',
            },
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='student_tier_rates',
            field=models.JSONField(blank=True, default=dict, help_text="JSON format for tier rates, e.g. {'1-200': 2000, '201-500': 1500, '501-1000': 1200, '1001+': 1000}"),
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('GRACE_PERIOD', 'Grace Period'), ('RESTRICTED', 'Restricted'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='compliance_threshold_percent',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='parent_subscription_amount',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='active_student_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='calculated_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='next_renewal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentplatformsubscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='studentplatformsubscription',
            name='billing_cycle',
            field=models.CharField(default='TERMLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentplatformsubscription',
            name='paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentplatformsubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_model',
            field=models.CharField(choices=[('PARENT_PAYS', 'Parent Pay'), ('SCHOOL_PAYS', 'School Pay'), ('HYBRID', 'Hybrid')], default='PARENT_PAYS', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='billing_model',
            field=models.CharField(choices=[('PARENT_PAYS', 'Model A (Parent Pays)'), ('SCHOOL_PAYS', 'Model B (School Pays)'), ('HYBRID', 'Model C (Hybrid Billing)')], default='PARENT_PAYS', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('TERMLY', 'Termly'), ('YEARLY', 'Yearly')], default='TERMLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='billing_model',
            field=models.CharField(default='PARENT_PAYS', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='payment_provider',
            field=models.CharField(default='Paystack', max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('EXPIRING_SOON', 'Expiring Soon'), ('DUE_TODAY', 'Due Today'), ('GRACE_PERIOD', 'Grace Period'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='ParentSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UNPAID', 'Unpaid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='UNPAID', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('paid_until', models.DateTimeField(blank=True, null=True)),
                ('academic_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.academicperiod')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.academicyear')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_subscriptions', to='people.parentprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Parent Subscription',
                'verbose_name_plural': 'Parent Subscriptions',
            },
        ),
        migrations.AddField(
            model_name='studentplatformsubscription',
            name='parent_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activated_students', to='tenants.parentsubscription'),
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('invoice_type', models.CharField(choices=[('SCHOOL', 'School Activation Invoice'), ('PARENT', 'Parent Access Invoice')], default='PARENT', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('due_date', models.DateTimeField()),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.school')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('tenant_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='tenants.tenantsubscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='parentsubscription',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_subscriptions', to='tenants.subscriptioninvoice'),
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('gateway', models.CharField(default='Paystack', max_length=50)),
                ('payment_method', models.CharField(choices=[('PAYSTACK', 'Paystack Online'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('POS', 'POS Terminal'), ('CHEQUE', 'Cheque')], default='PAYSTACK', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='INITIATED', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paid_on_behalf', models.BooleanField(default=False, help_text='True if school admin processed payment on behalf of parent')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.subscriptioninvoice')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_processed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('RENEWED', 'Renewed'), ('SUSPENDED', 'Suspended'), ('ACTIVATED', 'Activated'), ('PAYMENT', 'Payment Received'), ('MANUAL_OVERRIDE', 'Manual Override'), ('REMINDER', 'Reminder Sent')], max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.parentsubscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('tenant_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantsubscription')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.subscriptioninvoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.subscriptionpayment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['tenant', 'is_deleted'], name='tenants_sub_tenant__936fcd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parentsubscription',
            unique_together={('tenant', 'parent', 'academic_period')},
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['tenant', 'is_deleted'], name='tenants_sub_tenant__f63d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionauditlog',
            index=models.Index(fields=['tenant', 'is_deleted'], name='tenants_sub_tenant__083177_idx'),
        ),
    ]
