# Generated by Django 5.2.16 on 2026-08-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_billingsettings_subscriptionplan_is_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentsubscription',
            name='child_count',
            field=models.IntegerField(default=1, help_text='Number of children linked to parent'),
        ),
        migrations.AddField(
            model_name='parentsubscription',
            name='fee_per_child',
            field=models.DecimalField(decimal_places=2, default=5000.0, help_text='Base fee per child', max_digits=12),
        ),
        migrations.AlterField(
            model_name='parentsubscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount = fee_per_child * child_count', max_digits=12),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='parent_subscription_amount',
            field=models.DecimalField(decimal_places=2, default=5000.0, help_text='Termly fee per child', max_digits=12),
        ),
    ]
