# Generated by Django 5.2.16 on 2026-08-03 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_parentsubscription_child_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewaySetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('provider', models.CharField(choices=[('PAYSTACK', 'Paystack'), ('OPAY', 'OPay'), ('FLUTTERWAVE', 'Flutterwave'), ('MONIEPOINT', 'Moniepoint'), ('STRIPE', 'Stripe'), ('REMITA', 'Remita'), ('INTERSWITCH', 'Interswitch')], db_index=True, max_length=30, unique=True)),
                ('display_name', models.CharField(default='Payment Gateway', max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=1, help_text='Priority rank for failover: 1 = primary, 2 = secondary, etc.')),
                ('callback_url', models.CharField(blank=True, max_length=255)),
                ('webhook_url', models.CharField(blank=True, max_length=255)),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Provider specific metadata')),
            ],
            options={
                'verbose_name': 'Payment Gateway Setting',
                'verbose_name_plural': 'Payment Gateway Settings',
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='attempt_number',
            field=models.IntegerField(default=1, help_text='Payment attempt index for this invoice (Attempt 1, Attempt 2, etc.)'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='failover_occurred',
            field=models.BooleanField(default=False, help_text='True if automatic failover switched gateway'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='failover_reason',
            field=models.TextField(blank=True, help_text='Explanation if gateway failover occurred'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='requested_gateway',
            field=models.CharField(blank=True, help_text='Gateway initially requested by user (e.g. PAYSTACK)', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptionauditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('RENEWED', 'Renewed'), ('SUSPENDED', 'Suspended'), ('ACTIVATED', 'Activated'), ('PAYMENT', 'Payment Received'), ('REFUND_REQUESTED', 'Refund Requested'), ('REFUNDED', 'Refund Processed'), ('MANUAL_OVERRIDE', 'Manual Override'), ('REMINDER', 'Reminder Sent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='gateway',
            field=models.CharField(default='PAYSTACK', help_text='Actual gateway used for processing (e.g. OPAY)', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payment_method',
            field=models.CharField(choices=[('PAYSTACK', 'Paystack Online'), ('OPAY', 'OPay Wallet/Online'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('POS', 'POS Terminal'), ('CHEQUE', 'Cheque')], default='PAYSTACK', max_length=30),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('REFUND_REQUESTED', 'Refund Requested'), ('REFUNDED', 'Refunded')], default='INITIATED', max_length=20),
        ),
    ]
