# Generated by Django 5.2.16 on 2026-08-03 16:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_paymentgatewaysetting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingsettings',
            options={},
        ),
        migrations.AddField(
            model_name='paymentgatewaysetting',
            name='supports_refund',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentgatewaysetting',
            name='supports_webhook',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='billingsettings',
            name='reminder_schedule_days',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='paymentgatewaysetting',
            name='config_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='paymentgatewaysetting',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='attempt_number',
            field=models.IntegerField(default=1, help_text='Payment attempt index'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='failover_occurred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='failover_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='gateway',
            field=models.CharField(default='PAYSTACK', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='paid_on_behalf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='requested_gateway',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='MobileNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(default='GENERAL', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('data_payload', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mobile Notification',
                'verbose_name_plural': 'Mobile Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(default='Android', max_length=50)),
                ('app_version', models.CharField(default='1.0.0', max_length=30)),
                ('push_token', models.TextField(blank=True, help_text='Firebase Cloud Messaging (FCM) Token')),
                ('is_active', models.BooleanField(default=True)),
                ('last_active_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Device',
                'verbose_name_plural': 'User Devices',
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
