# Generated by Django 5.2.16 on 2026-07-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efbm', '0002_studentwallet_student_alter_studentwallet_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
