# Generated by Django 5.2.16 on 2026-07-30 05:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efbm', '0008_add_missing_ap_models'),
        ('tenants', '0003_remove_subscriptionplan_currency_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='supplierbill',
            name='efbm_suppli_tenant__094225_idx',
        ),
        migrations.AlterField(
            model_name='supplierbill',
            name='bill_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='supplierbill',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='supplierbill',
            name='issue_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='supplierbill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AddIndex(
            model_name='supplierbill',
            index=models.Index(fields=['tenant', 'status'], name='efbm_suppli_tenant__8c939c_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierbill',
            index=models.Index(fields=['tenant', 'due_date'], name='efbm_suppli_tenant__4af61a_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierbill',
            index=models.Index(fields=['supplier_name'], name='efbm_suppli_supplie_a449df_idx'),
        ),
    ]
