# Generated by Django 5.2.16 on 2026-07-30 05:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efbm', '0009_remove_supplierbill_efbm_suppli_tenant__094225_idx_and_more'),
        ('tenants', '0003_remove_subscriptionplan_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierledger',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_postings', to='efbm.supplierbill'),
        ),
        migrations.AlterField(
            model_name='supplierledger',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_postings', to='efbm.supplierpayment'),
        ),
        migrations.AlterField(
            model_name='supplierledger',
            name='reference_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='supplierledger',
            name='transaction_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='supplierledger',
            index=models.Index(fields=['tenant', 'transaction_date'], name='efbm_suppli_tenant__514af4_idx'),
        ),
    ]
