# Generated by Django 5.2.16 on 2026-07-30 05:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efbm', '0010_alter_supplierledger_bill_and_more'),
        ('tenants', '0003_remove_subscriptionplan_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierbalance',
            options={'ordering': ['-last_recalculated_at'], 'verbose_name': 'Supplier Balance', 'verbose_name_plural': 'Supplier Balances'},
        ),
        migrations.RemoveIndex(
            model_name='supplierbalance',
            name='efbm_suppli_tenant__1ffb2d_idx',
        ),
        migrations.RemoveField(
            model_name='supplierbalance',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='supplierbalance',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='supplierbalance',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='supplierbalance',
            name='last_recalculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierbalance',
            name='total_credit_notes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='supplierbalance',
            name='total_debit_notes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='supplierbalance',
            name='last_transaction_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierbalance',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='efbm.supplier'),
        ),
        migrations.AddIndex(
            model_name='supplierbalance',
            index=models.Index(fields=['tenant', 'supplier'], name='efbm_suppli_tenant__c53f52_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierbalance',
            index=models.Index(fields=['tenant', 'current_balance'], name='efbm_suppli_tenant__c6589f_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierbalance',
            index=models.Index(fields=['last_transaction_date'], name='efbm_suppli_last_tr_23841a_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierbalance',
            constraint=models.UniqueConstraint(fields=('tenant', 'supplier'), name='unique_supplier_balance_per_tenant'),
        ),
    ]
