# Generated by Django 5.2.16 on 2026-07-30 05:54

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efbm', '0011_alter_supplierbalance_options_and_more'),
        ('tenants', '0003_remove_subscriptionplan_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierstatement',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Supplier Statement', 'verbose_name_plural': 'Supplier Statements'},
        ),
        migrations.AlterUniqueTogether(
            name='supplierstatement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='supplierstatement',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='supplier_statements/excel/'),
        ),
        migrations.AddField(
            model_name='supplierstatement',
            name='generated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='supplierstatement',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierstatement',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='supplier_statements/pdf/'),
        ),
        migrations.AddField(
            model_name='supplierstatement',
            name='statement_end_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierstatement',
            name='statement_start_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierstatement',
            name='total_credits',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='supplierstatement',
            name='total_debits',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='supplierstatement',
            name='generated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierstatement',
            name='statement_number',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AddIndex(
            model_name='supplierstatement',
            index=models.Index(fields=['tenant', 'supplier'], name='efbm_suppli_tenant__86ec5b_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierstatement',
            index=models.Index(fields=['generated_at'], name='efbm_suppli_generat_0e723d_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierstatement',
            index=models.Index(fields=['statement_number'], name='efbm_suppli_stateme_f04c60_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierstatement',
            index=models.Index(fields=['statement_start_date', 'statement_end_date'], name='efbm_suppli_stateme_afbd5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierstatement',
            constraint=models.UniqueConstraint(fields=('tenant', 'supplier', 'statement_start_date', 'statement_end_date'), name='unique_supplier_statement_per_period'),
        ),
        migrations.RemoveField(
            model_name='supplierstatement',
            name='generation_date',
        ),
        migrations.RemoveField(
            model_name='supplierstatement',
            name='is_sent',
        ),
        migrations.RemoveField(
            model_name='supplierstatement',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='supplierstatement',
            name='period_start',
        ),
        migrations.RemoveField(
            model_name='supplierstatement',
            name='sent_date',
        ),
        migrations.RemoveField(
            model_name='supplierstatement',
            name='total_billed',
        ),
        migrations.RemoveField(
            model_name='supplierstatement',
            name='total_paid',
        ),
    ]
