# Generated by Django 5.2.16 on 2026-07-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efbm', '0012_alter_supplierstatement_options_and_more'),
        ('people', '0001_initial'),
        ('tenants', '0003_remove_subscriptionplan_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvallevel',
            options={'ordering': ['approval_matrix', 'level_order'], 'verbose_name': 'Approval Level', 'verbose_name_plural': 'Approval Levels'},
        ),
        migrations.AlterModelOptions(
            name='approvalmatrix',
            options={'ordering': ['min_amount'], 'verbose_name': 'Approval Matrix', 'verbose_name_plural': 'Approval Matrices'},
        ),
        migrations.AlterModelOptions(
            name='billapproval',
            options={'ordering': ['approval_level__level_order'], 'verbose_name': 'Bill Approval', 'verbose_name_plural': 'Bill Approvals'},
        ),
        migrations.AlterUniqueTogether(
            name='approvallevel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='billapproval',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='approvallevel',
            name='approval_type',
            field=models.CharField(choices=[('user', 'Specific User'), ('role', 'User Role'), ('department', 'Department Head'), ('amount_based', 'Amount-Based Rule')], default='role', max_length=20),
        ),
        migrations.AddIndex(
            model_name='approvallevel',
            index=models.Index(fields=['approval_matrix', 'level_order'], name='efbm_approv_approva_464334_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalmatrix',
            index=models.Index(fields=['tenant', 'is_active', 'min_amount'], name='efbm_approv_tenant__04705c_idx'),
        ),
        migrations.AddIndex(
            model_name='billapproval',
            index=models.Index(fields=['tenant', 'bill', 'status'], name='efbm_billap_tenant__a6647b_idx'),
        ),
        migrations.AddIndex(
            model_name='billapproval',
            index=models.Index(fields=['approver', 'status'], name='efbm_billap_approve_529d1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvallevel',
            constraint=models.UniqueConstraint(fields=('tenant', 'approval_matrix', 'level_order'), name='unique_approval_level_order_per_matrix'),
        ),
        migrations.AddConstraint(
            model_name='billapproval',
            constraint=models.UniqueConstraint(fields=('tenant', 'bill', 'approval_level'), name='unique_bill_approval_level_per_bill'),
        ),
    ]
