# Generated by Django 5.2.16 on 2026-07-30 06:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efbm', '0013_alter_approvallevel_options_and_more'),
        ('people', '0001_initial'),
        ('tenants', '0003_remove_subscriptionplan_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliercreditnote',
            options={'ordering': ['-issue_date', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='suppliercreditnote',
            name='efbm_suppli_tenant__59ce24_idx',
        ),
        migrations.AddField(
            model_name='suppliercreditnote',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliercreditnote',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_credit_notes', to='people.person'),
        ),
        migrations.AddField(
            model_name='suppliercreditnote',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='suppliercreditnote',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='suppliercreditnote',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliercreditnote',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_credit_notes', to='people.person'),
        ),
        migrations.AlterField(
            model_name='suppliercreditnote',
            name='issue_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='suppliercreditnote',
            name='note_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='suppliercreditnote',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='suppliercreditnote',
            index=models.Index(fields=['tenant', 'status'], name='efbm_suppli_tenant__ebc5a3_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercreditnote',
            index=models.Index(fields=['tenant', 'issue_date'], name='efbm_suppli_tenant__d984c0_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercreditnote',
            index=models.Index(fields=['bill', 'status'], name='efbm_suppli_bill_id_99d4a5_idx'),
        ),
    ]
