# Generated by Django 5.2.16 on 2026-07-30 08:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efbm', '0015_enhance_payment_voucher_models'),
        ('people', '0001_initial'),
        ('tenants', '0003_remove_subscriptionplan_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentvoucher',
            options={'ordering': ['-prepared_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='supplierdebitnote',
            options={'ordering': ['-issue_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='supplierpayment',
            options={'ordering': ['-payment_date', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='paymentvoucher',
            name='efbm_paymen_tenant__ebe6a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierdebitnote',
            name='efbm_suppli_tenant__4886e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierpayment',
            name='efbm_suppli_tenant__5f53b0_idx',
        ),
        migrations.RemoveField(
            model_name='supplierdebitnote',
            name='note_number',
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Bank Processed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierdebitnote',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierdebitnote',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_debit_notes', to='people.person'),
        ),
        migrations.AddField(
            model_name='supplierdebitnote',
            name='debit_note_number',
            field=models.CharField(db_index=True, default=2, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierdebitnote',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplierdebitnote',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierdebitnote',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_debit_notes', to='people.person'),
        ),
        migrations.AddField(
            model_name='supplierdebitnote',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplierdebitnote',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierdebitnote',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierdebitnote',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_debit_notes', to='people.person'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='efbm.supplierpayment'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='voucher_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='supplierdebitnote',
            name='issue_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='supplierdebitnote',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('wire_transfer', 'Wire Transfer'), ('ach_transfer', 'ACH Transfer'), ('cheque', 'Cheque Payment'), ('cash', 'Cash Payment'), ('electronic_payment', 'Electronic Payment')], default='bank_transfer', max_length=30),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='reference',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='paymentvoucher',
            index=models.Index(fields=['tenant', 'status'], name='efbm_paymen_tenant__16c144_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentvoucher',
            index=models.Index(fields=['voucher_number'], name='efbm_paymen_voucher_27fbaa_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentvoucher',
            index=models.Index(fields=['tenant', 'prepared_at'], name='efbm_paymen_tenant__30a4f0_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdebitnote',
            index=models.Index(fields=['tenant', 'status'], name='efbm_suppli_tenant__243daa_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdebitnote',
            index=models.Index(fields=['tenant', 'issue_date'], name='efbm_suppli_tenant__505ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdebitnote',
            index=models.Index(fields=['bill', 'status'], name='efbm_suppli_bill_id_251fca_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdebitnote',
            index=models.Index(fields=['debit_note_number'], name='efbm_suppli_debit_n_2ef795_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['tenant', 'status'], name='efbm_suppli_tenant__a6d127_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['tenant', 'payment_date'], name='efbm_suppli_tenant__3d92ac_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['payment_number'], name='efbm_suppli_payment_535814_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['reference'], name='efbm_suppli_referen_9c795f_idx'),
        ),
    ]
